---
# tasks file for nagios-ubuntu
- name: Installing Nagios Core Dependencies Packages on Ubuntu
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
    state: latest
    update_cache: yes

- name: Adding the group nagcmd
  group:
    name: nagcmd
    state: present

- name: Adding user Nagios
  user:
    name: nagios
    group: nagcmd

- name: Downloading and Extracting the Nagios Core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

- name: Configuring Nagios within the Ubuntu
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5

- name: Configuring Nagios using make clean
  make:
    chdir: /tmp/nagios-4.4.5
    target: clean

- name: Configuring Nagios using make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: Configuring Nagios using make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: Configuring Nagios using make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: Configuring Nagios using make install-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: Configuring Nagios using make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: Firing up the web Interface Installer
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: Installing passlib
  pip:
    name: passlib

- name: Adding user account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: "{{ username }}"
    password: "{{ password }}"

- name: a2enmod cgi
  command: a2enmod cgi

- name: Restarting apache2
  service:
  name: apache2
  state: restarted

- name: Installing Nagios Plugins for Ubuntu
  unarchive:
    src: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configuring Nagios Plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagcmd
  args:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configuring using make
  make:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configuring using make install
  make:
    target: install
    chdir: /tmp/nagios-plugins-2.3.3

- name: Enabling and Starting Nagios
  service:
    name: nagios
    enabled: yes
    state: started 
